name: Staging (Build)

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REPO_BASE: i40mc.azurecr.io/i40mp

jobs:
  build-and-push-image:
    name: Build and push image
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Docker registry authentication
        uses: azure/docker-login@v1
        with:
          login-server: i40mc.azurecr.io
          username: ${{ secrets.SP_I40MP_CI_CLIENT_ID }}
          password: ${{ secrets.SP_I40MP_CI_SECRET }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REPO_BASE }}/doghouse:${{ github.sha }},{{ env.REPO_BASE }}/doghouse:latest
